version: "3.8"

services:
  # iotdb:
  #   image: apache/iotdb:1.3.0-standalone
  #   container_name: iotflow_iotdb
  #   ports:
  #     - "6667:6667"    # IoTDB client port
  #     - "8181:8181"    # IoTDB web interface (if enabled)
  #   environment:
  #     - IOTDB_CONFIG_DIR=/iotdb/conf
  #   volumes:
  #     - iotdb_data:/iotdb/data
  #     - iotdb_logs:/iotdb/logs
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/6667' || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  redis:
    image: redis:7-alpine
    container_name: iotflow_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MQTT Broker - Eclipse Mosquitto
  mosquitto:
    image: eclipse-mosquitto:2.0.22-openssl
    container_name: iotflow_mosquitto
    ports:
      - "1883:1883"    # MQTT port
      - "9001:9001"    # WebSocket port
      - "8883:8883"    # MQTT SSL port
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/logs:/mosquitto/log
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -t test -m 'health check' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  # iotdb_data:
  #   driver: local
  iotdb_logs:
    driver: local
  redis_data:
    driver: local
  mosquitto_data:
    driver: local
